### ISSUE TITLE
unresolved import 'utilis.readdata'

### ISSUE THREAD

**Issue by mts-secops** [ltn21999/K-anonymity-and-Differential-Privacy-master#1]
hello there,
when i tried running your code i got the error: unresolved import 'utilis.readdata'
i was wondering which custom library is being used here?

**Comment by changzhang777** [comment]
the error: name 'AGECONFFILE' is not defined when i run k_anonymity.py
so what is the meaning of [AGECONFFILE, EDUCONFFILE, MARITALCONFFILE, RACECONFFILE] in class KAnonymity?

**Comment by mts-secops** [comment]
my issue got fixed. The problem of mine lays in the fact that my pc had configuration issues. my bad.
